name: HundredDaysDesert
version: '${project.version}'
main: dev.sasukector.hundreddaysbase.HundredDaysDesert
api-version: 1.17
authors: [ Sasukector ]
description: This is the core plugin for HundredDaysDesert
website: https://sasukector.dev
commands:
  played:
    description: Command to see played time of a player
    usage: /played [playerName]
  toggleDays:
    description: Command to toggle days display
    usage: /toggleDays
  conter-tps:
    description: Command to display tps
    usage: /tps